profiles/urls.py
from django.urls import path
from .views import ProfileView, UpdateProfile

app_name = 'profiles'

urlpatterns = [
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/update/', UpdateProfile.as_view(), name='update-profile'),
]

videos/urls.py
from django.contrib import admin
from django.urls import path
from .views import Index, CreateVideo, DetailVideo, UpdateVideo, DeleteVideo, VideoCategoryList, SearchVideo

app_name = 'videos'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('create/', CreateVideo.as_view(), name='video-create'),
    path('<int:pk>/', DetailVideo.as_view(), name='video-detail'),
    path('<int:pk>/update', UpdateVideo.as_view(), name='video-update'),
    path('<int:pk>/delete', DeleteVideo.as_view(), name='video-delete'),
    path('category/<int:pk>/', VideoCategoryList.as_view(), name='category-list'),
    path('search/', SearchVideo.as_view(), name='video-search'),
]

videoshare/urls.py
from django.contrib import admin
from django.urls import path, include
from videos import views as video_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', video_views.Index.as_view(), name='index'),
    path('videos/', include('videos.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, blank=True)
    location = models.CharField(max_length=80, blank=True)
    image = models.ImageField(upload_to='uploads/profile_pics', blank=True)

    def __str__(self):
        return f'{models.user.username} Profile'

profiles/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.Form):
    name = forms.CharField(max_length=30, label='Name')
    location = forms.CharField(max_length=80, label='Location')
    image = forms.ImageField(required=False)

    def clean(self):
        self.cleaned_data = super().clean()
        image = self.cleaned_data.get('image')
        if not image:
            self.cleaned_data['image'] = 'uploads/profile_pics/default.jpg'

    def signup(self, request, user):
        user.save()
        profile = Profile()
        profile.user = user
        profile.name = self.cleaned_data['name']
        profile.location = self.cleaned_data['location']
        profile.image = self.cleaned_data['image']
        profile.save()

profiles/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import View
from django.views.generic import UpdateView

from .models import Profile
from videos.models import Video


class ProfileView(View):

    def get(self, request, pk, *args, **kwargs):
        profile = get_object_or_404(Profile, pk=pk)
        videos = Video.objects.all().filter(uploader=pk).order_by('-date_post')

        context = {
            'profile': profile,
            'videos': videos,
        }

        return render(request, 'profiles/profile.html', context)


class UpdateProfile(UpdateView):
    model = Profile
    fields = ['name', 'location', 'image']
    template_name = 'profiles/update_profile.html'

    def form_valid(self, form):
        if not form.instance.image:
            form.instance.image = 'uploads/profile_pics/default.jpg'
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('profiles:profile', kwargs={'pk': self.object.pk})

profiles/templates/profiles/profile.html
{% extends 'videos/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="card col-md-6 col-sm-12 col-xs-12 d-flex flex-row align-items-center p-3 shadow">
            <img class="rounded-circle mr-4" height="150" width="150" src="{{ profile.image.url }}">
            <h1>{{ profile.user.username }}</h1>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="card col-md-6 col-sm-12 col-xs-12 p-3 shadow">
            <h5>Name: {{ profile.name }}</h5>
            <h5>Location: {{ profile.location }}</h5>
        </div>
    </div>

     {% if request.user == profile.user %}
        <div class="row justify-content-center mt-3">
            <div class="col-md-6 col-sm-12">
                <a href="{% url 'profiles:update-profile' profile.pk %}"><button class="btn btn-outline-info btn-block"><span><ion-icon class="mr-1" name="pencil-outline"></span>Edit Profile</button></a>
            </div>
        </div>
    {% endif %}

    <div class="row justify-content-center my-5">
        {% for video in videos %}
        <div class="card col-md-3 col-sm-12 col-xs-12 p-3 shadow mr-md-3 my-3">
            <img src="{{ video.thumbnail.url }}" class="card-img-top pt-2" alt="thumbnail">
                <div class="card-body">
                    <h5 class="card-title text-center">{{ video.title }}</h5>
                    <p class="card-text text-muted text-center"><span class="mr-4">{{ video.uploader }}</span><br><span>{{ video.date_post | date:"M d, Y" }}</span></p>
                    <a href="{% url 'videos:video-detail' video.pk %}" class="stretched-link"></a>
                </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

profiles/templates/profiles/update_profile.html
{% extends 'videos/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-12 col-xl-12">
            <form method="post" enctype="multipart/form-data" action="">
                {% csrf_token %}
                <legend class="border-bottom mb-4">Update Profile</legend>
                {{ form | crispy }}
                <button class="btn btn-outline-info btn-block mt-3" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}