profiles/urls.py
from django.urls import path
from .views import ProfileView, UpdateProfile

app_name = 'profiles'

urlpatterns = [
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/update/', UpdateProfile.as_view(), name='update-profile'),
]

videos/urls.py
from django.contrib import admin
from django.urls import path
from .views import Index, CreateVideo, DetailVideo, UpdateVideo, DeleteVideo, VideoCategoryList, SearchVideo

app_name = 'videos'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('create/', CreateVideo.as_view(), name='video-create'),
    path('<int:pk>/', DetailVideo.as_view(), name='video-detail'),
    path('<int:pk>/update', UpdateVideo.as_view(), name='video-update'),
    path('<int:pk>/delete', DeleteVideo.as_view(), name='video-delete'),
    path('category/<int:pk>/', VideoCategoryList.as_view(), name='category-list'),
    path('search/', SearchVideo.as_view(), name='video-search'),
]

videoshare/urls.py
from django.contrib import admin
from django.urls import path, include
from videos import views as video_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', video_views.Index.as_view(), name='index'),
    path('videos/', include('videos.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.core.validators import FileExtensionValidator


class Video(models.Model):
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    video_file = models.FileField(upload_to='uploads/video_files', validators=[FileExtensionValidator(allowed_extensions=['mp4'])])
    thumbnail = models.FileField(upload_to='uploads/thumbnails', validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    date_post = models.DateTimeField(default=timezone.datetime.now())
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return self.uploader_id


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey('Video', on_delete=models.CASCADE)
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Auhor: {self.author} | Created on: {self.created_on.strftime("%b %d %Y %I:%M %p")}'

videos/forms.py
from django import forms


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form_control',
            'placeholder': 'Leave a comment',
        }
    ))

videos/views.py
from django.db.models import Q
from django.shortcuts import render, reverse
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .forms import CommentForm
from .models import Video, Comment, Category

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class Index(ListView):
    model = Video
    template_name = 'videos/index.html'
    order_by = '-date_post'


class CreateVideo(LoginRequiredMixin, CreateView):
    model = Video
    fields = ['title', 'description', 'video_file', 'thumbnail', 'category']
    template_name = 'videos/create_video.html'

    def form_valid(self, form):
        form.instance.uploader = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('videos:video-detail', kwargs={'pk': self.object.pk})


class DetailVideo(DetailView):
    def get(self, request, pk, *args, **kwargs):
        video = Video.objects.get(pk=pk)

        categories = Video.objects.filter(category=video.category)[:15]

        form = CommentForm()
        comments = Comment.objects.filter(video=video).order_by('-created_on')
        context = {
            'object': video,
            'comments': comments,
            'categories': categories,
            'form': form,
        }
        return render(request, 'videos/detail_video.html', context)

    def post(self, request, pk, *args, **kwargs):
        video = Video.objects.get(pk=pk)

        categories = Video.objects.filter(category=video.category)[:15]

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                user = self.request.user,
                comment = form.cleaned_data['comment'],
                video = video
            )
            comment.save()

        comments = Comment.objects.filter(video=video).order_by('-created_on')
        context = {
            'object': video,
            'comments': comments,
            'categories': categories,
            'form': form
        }
        return render(request, 'videos/detail_video.html', context)


class UpdateVideo(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Video
    fields = ['title', 'description']
    template_name = 'videos/create_video.html'

    def get_success_url(self):
        return reverse('videos:video-detail', kwargs={'pk': self.object.pk})

    def test_func(self):
        video = self.get_object()
        return self.request.user == video.uploader


class DeleteVideo(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Video
    template_name = 'videos/delete_video.html'

    def get_success_url(self):
        return reverse('videos:index')

    def test_func(self):
        video = self.get_object()
        return self.request.user == video.uploader


class VideoCategoryList(View):
    def get(self, request, pk, *args, **kwargs):
        category = Category.objects.get(pk=pk)
        videos = Video.objects.filter(category=pk).order_by('-date_post')
        context = {
            'category': category,
            'videos': videos
        }

        return render(request, 'videos/video_category.html', context)


class SearchVideo(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get("q")

        query_list = Video.objects.filter(
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(uploader__username__icontains=query)
        )

        context = {
            'query_list': query_list,
        }

        return render(request, 'videos/search.html', context)

videos/templates/videos/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://unpkg.com/@videojs/themes@1/dist/sea/index.css" rel="stylesheet">

    <link href="https://vjs.zencdn.net/7.8.3/video-js.css" rel="stylesheet" />

    <link rel="stylesheet" type="text/css" href="/media/css/style.css">

    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
  	<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'videos/navigation.html' %}
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/sharer.js@latest/sharer.min.js"></script>
    <script src="https://vjs.zencdn.net/7.8.3/video.js"></script>
    <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
  </body>
</html>

videos/templates/videos/create_video.html
{% extends 'videos/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container mb-5">
	<div class="row justify-content-center">
		<div class="col-md-6 col-sm-12 col-xs-12">
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<legend class="border-bottom mb-4">Upload Video</legend>
				{{ form | crispy }}
				<button class="btn btn-outline-info btn-block mt-3" type="submit">Submit</button>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

videos/templates/videos/delete_video.html
{% extends 'videos/base.html' %}

{% block content %}

	<div class="container">
		<div class="row justify-content-center mt-5">
			<div class="col-md-6 col-sm-12 col-xs-12 text-center">
				<form method="POST">
					{% csrf_token %}
					<legend class="border-bottom mb-4">Delete Video</legend>
					<h5>Are You Sure?</h5>
					<p>This will delete the video forever.  This cannot be undone.</p>
					<button class="btn btn-outline-danger btn-block" type="submit">Delete</button>
				</form>
			</div>
		</div>
	</div>
	
{% endblock content %}

videos/templates/videos/detail_video.html
{% extends 'videos/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<div class="row mt-5">
			<div class="col-md-8 col-sm-12 col-xs-12">
				<video-js
					width="720"
					height="405"
					controls
					data-setup='{"playbackRates": [0.5, 1, 1.5, 2], "fluid": true}'>
					<source src="/media/{{ object.video_file }}" type="video/mp4">
					<p class="vjs-no-js">
					To view this video please enable Javascript, and consider upgrading to a web browser that <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
					</p>
				</video-js>

				<h5 class="mt-4">{{ object.title }}</h5>

				<div class="row">
					<div class="col-md-6 text-muted">
						<p>{{ object.date_post | date:"M d, Y" }}</p>
                        <a class="category-link" href="{% url 'videos:category-list' object.category.pk %}">{{ object.category }}</a>
					</div>
					<div class="col-md-6 text-muted text-right">
						<ion-icon class="video-icons" name="share-social-outline" type="button"  data-toggle="modal" data-target="#exampleModal">
                        Share
                    </ion-icon>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Share This Video!</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body text-center">
                                <ion-icon class="social-share-icons twitter-social-color" name="logo-twitter" data-sharer="twitter" data-title="Checkout {{ object.title }}!" data-hashtags="" data-url="http://localhost:8000/videos/{{ object.pk }}">Share on Twitter</ion-icon>
                                <ion-icon class="social-share-icons facebook-social-color" name="logo-facebook" data-sharer="facebook" data-title="Checkout {{ object.title }} by {{ object.uploader }}!" data-hashtags="" data-url="http://localhost:8000/videos/{{ object.pk }}">Share on Facebook</ion-icon>
                                <ion-icon class="social-share-icons reddit-social-color" name="logo-reddit" data-sharer="reddit" data-title="Checkout {{ object.title }} by {{ object.uploader }}!" data-hashtags="" data-url="http://localhost:8000/videos/{{ object.pk }}">Share on Reddit</ion-icon>
                                <p class="mt-3">Link: http://localhost:8000/videos/{{ object.pk }}</p>
                            </div>
                        </div>
                        </div>
                    </div>
			        </div>
		        </div>

                {% if object.uploader == user %}
                    <a class="video-icons icon-color" href="{% url 'videos:video-update' object.pk %}"><ion-icon name="pencil-outline"></ion-icon></a>
                    <a class="video-icons icon-color" href="{% url 'videos:video-delete' object.pk %}"><ion-icon name="close-outline"></ion-icon></a>
                {% endif %}
	        </div>
            <div class="col-md-4 col-sm-12 col-xs-12">
                <h3 class="text-center mb-3">Similar Videos</h3>
                {% for category in categories %}
                {% if object.pk != category.pk %}
                <div class="position-relative d-flex flex-row mb-5 py-2 border-bottom">
                    <img src="{{ category.thumbnail.url }}" width="100" height="50" />
                    <h5 class="pl-3">{{ category.title }}</h5>
                    <a href="{% url 'videos:video-detail' category.pk %}" class="stretched-link"></a>
                </div>
                {% endif %}
                {% endfor %}
		    </div>
        </div>

        <div class="row">
            <div class="col-md-8 my-3 border-bottom">
                <p>{{ object.description }}</p>
            </div>
	    </div>

        <!-- Comments -->
        <div class="row mt-3">
            <div class="col-md-8 col-sm-12">
                {% if user.is_authenticated %}
                <form method="POST">
                    {% csrf_token %}
                    <legend class="border-bottom mb-4">Leave a Comment!</legend>
                    {{ form | crispy }}
                    <button class="btn btn-outline-info btn-block">Post</button>
                </form>
                {% else %}
                <a class="btn btn-outline-info btn-block" href="{% url 'account_login' %}">Sign In To Post a Comment!</a>
                {% endif %}
            </div>
        </div>

        {% for comment in comments %}
        <div class="row mt-3">
            <div class="col-md-8 col-sm-12 border-bottom">
                <h5>{{ comment.user }} says:</h5>
                <p>{{ comment.comment }}</p>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock content %}

videos/templates/videos/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <a class="navbar-brand" href="{% url 'videos:index' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0 d-flex flex-row" method="get" action="{% url 'videos:video-search' %}">
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
            <button class="search-button" type="submit"><ion-icon name="search-outline"></ion-icon></button>
        </form>
      <ul class="navbar-nav mr-auto">
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'videos:video-create' %}">Upload Video</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profiles:profile' user.profile.pk %}"><img src="{{ user.profile.image.url }}" width="35" height="35" class="d-inline-block rounded-circle" alt="Profile"></a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

videos/templates/videos/search.html
{% extends 'videos/base.html' %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			{% for object in query_list %}
			<div class="card col-md-3 col-sm-12 mr-md-2 mt-5 p-3 border-0">
				<a href="{% url 'videos:video-detail' object.pk %}"><img src="/media/{{ object.thumbnail }}" width="256" height="144"></a>
				<div class="card-body">
					<a class="link-text" href="{% url 'videos:video-detail' object.pk %}"><h5 class="text-center">{{ object.title }}</h5></a>
					<p class="text-muted text-center m-0">{{ object.uploader }}</p>
					<p class="text-muted text-center">{{ object.date_post | date:"M d, Y" }}</p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock content %}

videos/templates/videos/video_category.html
{% extends 'videos/base.html' %}

{% block content %}
	<div class="container">
        <div class="row">
            <div class="col-md-12 my-3">
                <h2>{{ category.name }} Videos</h2>
            </div>
        </div>
		<div class="row justify-content-center">
			{% for video in videos %}
			<div class="card col-md-3 col-sm-12 mr-md-2 mt-5 p-3 border-0">
				<a href="{% url 'videos:video-detail' video.pk %}"><img src="/media/{{ video.thumbnail }}" width="256" height="144"></a>
				<div class="card-body">
					<a class="link-text" href="{% url 'videos:video-detail' video.pk %}"><h5 class="text-center">{{ video.title }}</h5></a>
					<p class="text-muted text-center m-0">{{ video.uploader }}</p>
					<p class="text-muted text-center">{{ video.date_post | date:"M d, Y" }}</p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock content %}